list1 = ["Accounting and Finance (MSc)",
"Accounting and Society (Online Distance Learning) (MSc)",
"Acoustics and Music Technology (MSc)",
"Acoustics and Music Technology (MSc)",
"Advanced Arabic (MSc)",
"Advanced Chemical Engineering (MSc)",
"Advanced Design Informatics (MSc)",
"Advanced Professional Studies (Adult Protection) PgCert",
"Advanced Professional Studies (Mental Health Officer Award) (PgCert)",
"Advanced Sustainable Design (Mixed Mode) (MSc)",
"Advanced Sustainable Design (On Campus) (MSc)",
"Advancing Nursing Practice (MSc)",
"Advancing Nursing Practice (MSc)",
"Advancing Nursing Practice (MSc)",
"Africa and International Development (MSc)",
"Africa and International Development (MSc)",
"Africa and International Development (Online Distance Learning) (PgCert)",
"African Studies (MSc)",
"African Studies (MSc)",
"American History (MSc)",
"American History (MSc)",
"Anatomical Sciences (PgCert) (Online Distance Learning)",
"Anatomical Sciences (PgDip) (Online Distance Learning)",
"Ancient History (MSc)",
"Ancient History (MSc)",
"Ancient Philosophy (MSc)",
"Ancient Philosophy (MSc)",
"Animal Biosciences (MSc)",
"Animal Breeding and Genetics (MSc)",
"Animal Breeding and Genetics (MSc)",
"Animal Breeding and Genetics (PgDip)",
"Animation (MFA)",
"Applied Animal Behaviour and Animal Welfare (MSC)",
"Applied Animal Behaviour and Animal Welfare (MSc)",
"Applied Animal Behaviour and Animal Welfare (MSc)",
"Applied Animal Behaviour and Animal Welfare (MSc)",
"Applied Linguistics (MSc)",
"Applied Linguistics (MSc)",
"Archaeology (MSc)",
"Archaeology (MSc)",
"Architectural and Urban Design (MSc)",
"Architectural Conservation (MSc)",
"Architectural Conservation (MSc)",
"Architectural History and Theory (MSc)",
"Architectural History and Theory (MSc)",
"Architecture (MArch)",
"Art in the Global Middle Ages (MSc)",
"Art in the Global Middle Ages (MSc)",
"Art, Space and Nature (MA (eca))",
"Art, Space and Nature (MFA)",
"Artificial Intelligence (MSc)",
"Artificial Intelligence (MSc)",
"Artificial Intelligence (MSc)",
"Banking and Risk (MSc)",
"Biblical Studies (MSc)",
"Biblical Studies (MSc)",
"Biblical Studies (MTh)",
"Biblical Studies (MTh)",
"Biochemistry (MSC)",
"Biochemistry (PgDip)",
"Biodiversity and Taxonomy of Plants (MSc)",
"Biodiversity and Taxonomy of Plants (MSc)",
"Biodiversity and Taxonomy of Plants (PgDip)",
"Biodiversity, Wildlife and Ecosystem Health (Online Distance Learning) (MSc)",
"Biodiversity, Wildlife and Ecosystem Health (Online Distance Learning) (PgCert)",
"Biodiversity, Wildlife and Ecosystem Health (Online Distance Learning) (PgDip)",
"Bioinformatics (MSc)",
"Bioinformatics (PgDip)",
"Biotechnology (MSc)",
"Biotechnology (PgDip)",
"Book History and Material Culture (MSc)",
"Book History and Material Culture (MSc)",
"Business Administration (MBA)",
"Business Administration with International Exchange (MBA)",
"Business Analytics (MSc)",
"Carbon Capture and Storage (MSc)",
"Carbon Capture and Storage (MSc)",
"Carbon Finance (MSc)",
"Carbon Innovation (PG Cert) (Online Distance Learning)",
"Carbon Management (MSC)",
"Carbon Management (MSC)",
"Carbon Management (Online Distance Learning) (MSc)",
"Carbon Management (Online Distance Learning) (MSc)",
"Carbon Management (Online Distance Learning) (Pg Dip)",
"Celtic and Scottish Studies MSc",
"Celtic and Scottish Studies MSc",
"Childhood Studies (MSc)",
"Childhood Studies (MSc)",
"Children and Young People's Mental Health and Psychological Practice (MSc)",
"Children and Young People's Mental Health and Psychological Practice (MSc)",
"Children and Young People's Mental Health and Psychological Practice (Online Distance Learning) (MSc)",
"Children and Young People's Mental Health and Psychological Practice (PgDip)",
"Chinese Society and Culture (MSc)",
"Chinese Society and Culture (MSc)",
"Chinese Studies (MCS)",
"Classical Art and Archaeology (MSc)",
"Classical Art and Archaeology (MSc)",
"Classics (MSc)",
"Classics (MSc)",
"Climate Change Management (Online Distance Learning) Pg Cert",
"Clinical Animal Behaviour (Online Distance Learning) (MSc)",
"Clinical Education (Online Distance Learning) (MSc)",
"Clinical Education (Online Distance Learning) (PgCert)",
"Clinical Education (Online Distance Learning) (PgDip)",
"Clinical Management of Pain (Online Distance Learning) (MSc)",
"Clinical Microbiology and Infectious Diseases (Online Distance Learning) (MSc)",
"Clinical Microbiology and Infectious Diseases (Online Distance Learning) (PgCert)",
"Clinical Microbiology and Infectious Diseases (Online Distance Learning) (PgDip)",
"Clinical Ophthalmology (Online Distance Learning) (ChM)",
"Clinical Trials (MSc) (Online Distance Learning)",
"Clinical Trials (PgCert) (Online Distance Learning)",
"Clinical Trials (PgDip) (Online Distance Learning)",
"Cognition in Science and Society (MSc)",
"Cognition in Science and Society (MSc)",
"Cognitive Science (MSc)",
"Cognitive Science (MSc)",
"Cognitive Science (MSc)",
"Commercial Law (LLM)",
"Commercial Law (LLM)",
"Commercial Law and Chinese (LLM)",
"Comparative and European Private Law (LLM)",
"Comparative and European Private Law (LLM)",
"Comparative Literature (MSc)",
"Comparative Literature (MSc)",
"Comparative Public Policy (MSc)",
"Comparative Public Policy (MSc)",
"Competition Law and Innovation (LLM)",
"Composition (MMus)",
"Composition (MMus)",
"Composition for Screen (MSc)",
"Composition for Screen (MSc)",
"Computational Applied Mathematics (MSc)",
"Computational Chemistry and Modelling (Online Distance Learning) (PgCert)",
"Computational Chemistry and Modelling (UoE lead with University of St Andrews) (Online Distance Learning) (PgCert)",
"Computational Mathematical Finance (MSc)",
"Computational Mathematical Finance (MSc)",
"Computational Mathematical Finance (PgDip)",
"Computational Mathematical Finance (PgDip)",
"Computer Science (MSc)",
"Computer Science (MSc)",
"Computer Science (MSc)",
"Conservation Medicine (MVetSci ) (Online Distance Learning)",
"Conservation Medicine (PgCert) (Online Distance Learning)",
"Conservation Medicine (PgDip) (Online Distance Learning)",
"Contemporary Art Practice (MA (eca))",
"Contemporary Art Practice (MA (eca))",
"Contemporary Art Practice (MFA)",
"Contemporary Art Theory (MA (eca))",
"Contemporary Art Theory (MA (eca))",
"Contemporary History (MSc)",
"Contemporary History (MSc)",
"Corporate Law (LLM)",
"Corporate Law (LLM)",
"Counselling (Interpersonal Dialogue) (MCouns)",
"Counselling (MCouns)",
"Counselling (PgDip)",
"Counselling Studies (MSc)",
"Counselling Studies (MSc)",
"Counselling Studies (MSc)",
"Counselling Studies (PgCert)",
"Creative Writing (MSc)",
"Criminal Law (LLM)",
"Criminal Law (LLM)",
"Criminal Law and Criminal Justice (LLM)",
"Criminal Law and Criminal Justice (LLM)",
"Criminology and Criminal Justice (ESRC track) (MSc)",
"Criminology and Criminal Justice (MSc)",
"Criminology and Criminal Justice (MSc)",
"Cultural Landscapes (MSc)",
"Cultural Studies (MSc)",
"Cultural Studies (MSc)",
"Dance Science and Education (MSc)",
"Dance Science and Education (MSc)",
"Dance Science and Education (PgDip)",
"Dance Science and Education with TQs (MSc)",
"Dance Science and Education with TQs (MSc)",
"Data Science (MSc)",
"Data Science (MSc)",
"Data Science (MSc)",
"Data Science, Technology and Innovation (Anaesthesia and Critical Care) (Online Distance Learning) (PgDip)",
"Dental Implantology (MSc)",
"Design and Digital Media (MSc)",
"Design and Digital Media (MSc)",
"Design Informatics (MA (eca))",
"Design Informatics (MFA)",
"Design Informatics (MSc)",
"Developmental Cognitive Science (MSc)",
"Developmental Cognitive Science (MSc)",
"Developmental Linguistics (MSc)",
"Developmental Linguistics (MSc)",
"Digital Composition and Performance (MSc)",
"Digital Composition and Performance (MSc)",
"Digital Education (Online Distance Learning) (MSC)",
"Digital Media Design (Online Distance Learning) (MSc)",
"Digital Society (MSc)",
"Digital Society (MSc)",
"Drug Discovery and Translational Biology (MSc)",
"Drug Discovery and Translational Biology (PgDip)",
"Earth Observation and Geoinformation Management (MSc)",
"Earth Observation and Geoinformation Management (MSc)",
"Earth Observation and Geoinformation Management (MSc)",
"East Asian Relations (MSc)",
"East Asian Relations (MSc)",
"Ecological Economics (SAC) (MSc)",
"Ecological Economics (SAC) (MSc)",
"Ecological Economics (SAC) (MSc)",
"Economics (Econometrics) (MSC)",
"Economics (Econometrics) (MSC)",
"Economics (Finance) (MSc)",
"Economics (Finance) (MSc)",
"Economics (MSc)",
"Economics (MSc)",
"Ecosystem Services (MSc)",
"Ecosystem Services (MSc)",
"Ecosystem Services (MSc)",
"Education (Child and Adolescent Psychology) (MSc)",
"Education (Child and Adolescent Psychology) (MSc)",
"Education (Child and Adolescent Psychology) (MSc)",
"Education (Comparative Education and International Development) (MSc)",
"Education (Comparative Education and International Development) (MSc)",
"Education (Comparative Education and International Development) (MSc)",
"Education (Learning in Communities) (MSc)",
"Education (Learning in Communities) (MSC)",
"Education (Learning in Communities) (MSc)",
"Education (MSc)",
"Education (MSc)",
"Education (MSc)",
"Education (Philosophy of Education) (MSc)",
"Education (Philosophy of Education) (MSc)",
"Education (Philosophy of Education) (MSc)",
"Education (Physical Education and Well being) (MSc)",
"Education (Physical Education and Well being) (MSc)",
"Education (Physical Education and Well being) (MSc)",
"Education (Research   ESRC) (MSc)",
"Education (Research) (MSc)",
"Education (Research) (MSc)",
"Education (Research) (MSc)",
"Education: Language   theory, practice and literacy (MSc)",
"Education: Language   theory, practice and literacy (PgCert)",
"Education: Language   theory, practice and literacy (PgDip)",
"Electrical Power Engineering (MSc)",
"Electronics (MSc)",
"Energy, Society and Sustainability (MSc)",
"Energy, Society and Sustainability (MSc)",
"English Language (MSc)",
"English Language (MSc)",
"English Literature: United States Literature   Cultural Values from Revolution to Empire (MSc)",
"English Literature: United States Literature   Cultural Values from Revolution to Empire (MSc)",
"Entrepreneurship and Innovation (MSc)",
"Environment and Development (MSc)",
"Environment and Development (MSc)",
"Environment and Development (MSc)",
"Environment, Culture and Society (MSc)",
"Environment, Culture and Society (MSc)",
"Environmental Protection and Management (SAC) (MSc)",
"Environmental Protection and Management (SAC) (MSc)",
"Environmental Protection and Management (SAC) (MSc)",
"Environmental Sustainability (MSc)",
"Environmental Sustainability (MSc)",
"Environmental Sustainability (MSc)",
"Epistemology, Ethics and Mind (MSC) (Online Distance Learning)",
"Epistemology, Ethics and Mind (PgDip) (Online Distance Learning)",
"Equine Science (Online Distance Learning) (MSc)",
"Equine Science (Online Distance Learning) (PgDip)",
"Ethics (MSc)",
"Ethics (MSc)",
"Ethics (MTh)",
"Ethics (MTh)",
"European Archaeology (MSc)",
"European Archaeology (MSc)",
"European Law (LLM)",
"European Law (LLM)",
"Evolution of Language and Cognition (MSc)",
"Evolution of Language and Cognition (MSc)",
"Evolutionary Genetics (MSc)",
"Evolutionary Genetics (MSc)",
"Evolutionary Genetics (PgDip)",
"Executive Business Administration (MBA)",
"Family Medicine (MFM) (Online Distance Learning)",
"Fashion (MFA)",
"Film Directing (MA (eca))",
"Film Directing (MFA)",
"Film Studies (MSc)",
"Film Studies (MSc)",
"Film, Exhibition and Curation (MSc)",
"Film, Exhibition and Curation (MSc)",
"Finance (MSc)",
"Financial Mathematics (jointly with Heriot Watt University) (MSc)",
"Financial Modelling and Optimization (MSc)",
"Financial Modelling and Optimization (MSc)",
"Financial Modelling and Optimization (PgDip)",
"Food Security (SAC) (MSc)",
"Food Security (SAC) (MSc)",
"Food Security (SAC) (MSc)",
"Gender History (MSc)",
"General Surgery (Online Distance Learning) (ChM)",
"Geographical Information Science (MSc)",
"Geographical Information Science (MSc)",
"Geographical Information Science (MSc)",
"Geographical Information Science and Archaeology (MSc)",
"Geographical Information Science and Archaeology (MSc)",
"Geographical Information Science and Archaeology (MSc)",
"Glass (MA (eca))",
"Glass (MFA)",
"Global Challenges (Online Distance Learning) MSc",
"Global Challenges (Online Distance Learning) Pg Dip",
"Global Crime, Justice and Security (MSc)",
"Global Crime, Justice and Security (MSc)",
"Global Crime, Justice and Security (MSc)",
"Global Development Challenges (Online Distance Learning) (PgCert)",
"Global eHealth (Online Distance Learning) (MSc)",
"Global eHealth (Online Distance Learning) (PgCert)",
"Global eHealth (Online Distance Learning) (PgDip)",
"Global Environment and Climate Change Law (LLM)",
"Global Environment and Climate Change Law (LLM)",
"Global Environment, Politics and Society (MSc)",
"Global Environment, Politics and Society (Msc)",
"Global Environmental Challenges (Distance Learning) (PgCert)",
"Global Health and Infectious Diseases (Online Distance Learning) (MSc)",
"Global Health and Infectious Diseases (Online Distance Learning) (PgCert)",
"Global Health and Infectious Diseases (Online Distance Learning) (PgDip)",
"Global Health and Public Policy (MSc)",
"Global Health and Public Policy (MSc)",
"Global Health and Public Policy (MSc)",
"Global Health Challenges (Online Distance Learning) (PgCert)",
"Global Health Policy (MSc)",
"Global Health Policy (MSc)",
"Global Health Policy (Online Distance Learning) (PgCert)",
"Global Health Policy (Online Distance Learning) (PgCert)",
"Global Health: Non Communicable Diseases (Online Distance Learning) (MSc)",
"Graphic Design (MA (eca))",
"Graphic Design (MFA)",
"Health Policy (MSc)",
"Health Policy (MSc)",
"High Performance Computing (MSc)",
"High Performance Computing (MSc)",
"High Performance Computing (PgDip)",
"High Performance Computing with Data Science (MSc)",
"High Performance Computing with Data Science (MSc)",
"High Performance Computing with Data Science (MSc)",
"History (MSc)",
"History (MSc)",
"History (ODL) MSc",
"History of Art, Theory and Display (MSc)",
"History of Art, Theory and Display (MSc)",
"Human Anatomy (MSc)",
"Human Anatomy (PgDip)",
"Human Cognitive Neuropsychology (MSc)",
"Human Cognitive Neuropsychology (MSc)",
"Human Complex Trait Genetics (MSc)",
"Human Complex Trait Genetics (MSc)",
"Human Complex Trait Genetics (PgDip)",
"Human Osteoarchaeology (MSc)",
"Human Resource Management (MSc)",
"Human Rights (LLM)",
"Human Rights (LLM)",
"Illustration (MA (eca))",
"Illustration (MFA)",
"Inclusive Education (Bilingual Learners) (PgDip)",
"Inclusive Education (Deaf Learners) (PgDip)",
"Inclusive Education (MSc)",
"Inclusive Education (MSc)",
"Inclusive Education (PgDip)",
"Inclusive Education (PgDip)",
"Inclusive Education (Visually Impaired Learners) (PgDip)",
"Informatics (MSc)",
"Informatics (MSc)",
"Informatics (MSc)",
"Information Technology Law (Online Distance Learning) (LLM)",
"Information Technology Law (Online Distance Learning) (LLM)",
"Information Technology Law (Online Distance Learning) (LLM)",
"Information Technology Law (Online Distance Learning) (LLM)",
"Information Technology Law (Online Distance Learning) (LLM)",
"Innovation, Technology and the Law (LLM)",
"Innovation, Technology and the Law (LLM)",
"Innovation, Technology and the Law (Online Distance Learning) (LLM)",
"Innovation, Technology and the Law (Online Distance Learning) (LLM)",
"Innovation, Technology and the Law (Online Distance Learning) (LLM)",
"Innovation, Technology and the Law (Online Distance Learning) (LLM)",
"Innovation, Technology and the Law (Online Distance Learning) (LLM)",
"Intellectual History (MSc)",
"Intellectual History (MSc)",
"Intellectual Property Law (LLM)",
"Intellectual Property Law (LLM)",
"Intellectual Property Law (Online Distance Learning) (LLM)",
"Intellectual Property Law (Online Distance Learning) (LLM)",
"Intellectual Property Law (Online Distance Learning) (LLM)",
"Intellectual Property Law (Online Distance Learning) (LLM)",
"Intellectual Property Law (Online Distance Learning) (LLM)",
"Intellectual Property Law and Chinese (LLM)",
"Interior Design (MA (eca))",
"Internal Medicine (Online Distance Learning) (MSc)",
"Internal Medicine (Online Distance Learning) (PgCert)",
"Internal Medicine (Online Distance Learning) (PgDip)",
"International and European Politics (MSc)",
"International and European Politics (MSc)",
"International Animal Health (Online Distance Learning) (MSc)",
"International Animal Health (Online Distance Learning) (PgCert)",
"International Animal Health (Online Distance Learning) (PgDip)",
"International Animal Welfare, Ethics & Law (Online Distance Learning) (MSc)",
"International Animal Welfare, Ethics & Law (Online Distance Learning) (PgCert)",
"International Animal Welfare, Ethics & Law (Online Distance Learning) (PgDip)",
"International Banking Law and Finance (LLM)",
"International Business and Emerging Markets (MSc)",
"International Commercial Law and Practice(Online Distance Learning) (LLM)",
"International Commercial Law and Practice(Online Distance Learning) (LLM)",
"International Commercial Law and Practice(Online Distance Learning) (LLM)",
"International Commercial Law and Practice(Online Distance Learning) (LLM)",
"International Commercial Law and Practice(Online Distance Learning)(LLM)",
"International Development (MSc)",
"International Development (MSc)",
"International Development (Online Distance Learning) (MSc)",
"International Development (Online Distance Learning) (MSc)",
"International Development (Online Distance Learning) (PgCert)",
"International Development (Online Distance Learning) (PgDip)",
"International Economic Law (LLM)",
"International Economic Law (LLM)",
"International Human Resource Management (MSc)",
"International Law (LLM)",
"International Law (LLM)",
"International Law and Chinese (LLM)",
"International Political Theory (MSc)",
"International Political Theory (MSc)",
"International Relations (MSc)",
"International Relations (MSc)",
"International Relations of the Middle East (MSc)",
"International Relations of the Middle East (MSc)",
"International Relations of the Middle East with Advanced Arabic (MSc)",
"International Relations of the Middle East with Arabic (MSc)",
"International Social Work and Social Development (MSc)",
"International Social Work and Social Development (MSc)",
"Islamic and Middle Eastern Studies (MSc)",
"Islamic and Middle Eastern Studies (MSc)",
"Japanese Society and Culture (MSc)",
"Japanese Society and Culture (MSc)",
"Jewellery (MFA)",
"Landscape and Wellbeing (MSc)",
"Landscape and Wellbeing (MSc)",
"Landscape Architecture (European Masters) (EMiLA)",
"Landscape Architecture (MLA)",
"Language Teaching (MSc)",
"Language Teaching (MSc)",
"Language Teaching (PgDip)",
"Language Teaching (PgDip)",
"Late Antique, Islamic and Byzantine Studies (MSc)",
"Late Antique, Islamic and Byzantine Studies (MSc)",
"Law (LLM)",
"Law (LLM)",
"Law (Online Distance Learning) (LLM)",
"Law (Online Distance Learning) (LLM)",
"Law (Online Distance Learning) (LLM)",
"Law (Online Distance Learning) (LLM)",
"Law (Online Distance Learning) (LLM)",
"Law (Online Distance Learning) (PgCert)",
"Law (Online Distance Learning) (PgCert)",
"Law (Online Distance Learning) (PgCert)",
"Law (Online Distance Learning) (PgCert)",
"Law and Chinese (LLM)",
"Learning for Sustainability (MSC)",
"Learning for Sustainability (Pg Dip)",
"Linguistics (MSc)",
"Linguistics (MSc)",
"Literature and Modernity: 1900 to the Present (MSc)",
"Literature and Modernity: 1900 to the Present (MSc)",
"Literature and Society: Enlightenment, Romantic and Victorian (MSc)",
"Literature and Society: Enlightenment, Romantic and Victorian (MSc)",
"Management (MSc)",
"Management of Bioeconomy, Innovation and Governance (MSc)",
"Management of Bioeconomy, Innovation and Governance (MSc)",
"Marine Systems and Policies (MSc)",
"Marine Systems and Policies (MSc)",
"Marine Systems and Policies (MSc)",
"Marketing (MSc)",
"Marketing and Business Analysis (MSc)",
"Master of Public Health (MPH) (Online Distance Learning)",
"Master of Public Policy (MPP)",
"Material Practice (MSc)",
"Materials Chemistry (MSc)",
"Mathematical Physics MSc",
"Medical Anthropology (MSc)",
"Medical Anthropology (MSc)",
"Medical Law and Ethics (LLM)",
"Medical Law and Ethics (LLM)",
"Medical Law and Ethics (Online Distance Learning) (LLM)",
"Medical Law and Ethics (Online Distance Learning) (LLM)",
"Medical Law and Ethics (Online Distance Learning) (LLM)",
"Medical Law and Ethics (Online Distance Learning) (LLM)",
"Medical Law and Ethics (Online Distance Learning) (LLM)",
"Medicinal and Biological Chemistry (MSc)",
"Medieval History (MSc)",
"Medieval History (MSc)",
"Medieval Literatures and Cultures (MSc)",
"Medieval Literatures and Cultures (MSc)",
"Mediterranean Archaeology (MSc)",
"Mediterranean Archaeology (MSc)",
"Middle Eastern Studies with Advanced Arabic (MSc)",
"Middle Eastern Studies with Arabic (MSc)",
"Mind, Language and Embodied Cognition (MSc)",
"Mind, Language and Embodied Cognition (MSc)",
"Ministry (MSc)",
"Ministry (MSc)",
"Ministry (MTh)",
"Ministry (MTh)",
"Modern and Contemporary Art: History, Curating, Criticism (MSc)",
"Modern and Contemporary Art: History, Curating, Criticism (MSc)",
"Musical Instrument Research (MMus)",
"Musical Instrument Research (MMus)",
"Musicology (MMus)",
"Musicology (MMus)",
"Nationalism Studies (MSc)",
"Nationalism Studies (MSc)",
"Operational Research (MSc)",
"Operational Research (MSc)",
"Operational Research (PgDip)",
"Operational Research with Computational Optimization (MSc)",
"Operational Research with Computational Optimization (MSc)",
"Operational Research with Computational Optimization (PgDip)",
"Operational Research with Data Science (MSc)",
"Operational Research with Data Science (MSc)",
"Operational Research with Data Science (MSc)",
"Operational Research with Risk (MSc)",
"Operational Research with Risk (MSc)",
"Operational Research with Risk (PgDip)",
"Oral Surgery (DClinDent)",
"Oral Surgery (MClinDent)",
"Orthodontics (DClinDent)",
"Orthodontics (MClinDent)",
"Outdoor Education (MSc)",
"Outdoor Education (PgDip)",
"Outdoor Environmental and Sustainability Education (MSc)",
"Outdoor Environmental and Sustainability Education (PgDip)",
"Paediatric Dentistry (DClinDent)",
"Paediatric Dentistry (MClinDent)",
"Paediatric Emergency Medicine (Online Distance Learning)  (PgDip)",
"Paediatric Emergency Medicine (Online Distance Learning) (MSc)",
"Paediatric Emergency Medicine (Online Distance Learning) (PgCert)",
"Particle and Nuclear Physics (MSc)",
"Performance Costume (MFA)",
"Performance Psychology (MSc)",
"Performance Psychology (PgDip)",
"Persian Civilisation (MSc)",
"Persian Civilisation (MSc)",
"Personal and Social Outdoor Education (MSc)",
"Personal and Social Outdoor Education (PgDip)",
"Philosophy (MSc)",
"Philosophy (MSc)",
"Philosophy, Science and Religion (Online Distance Learning) (MSc)",
"Philosophy, Science and Religion (Online Distance Learning) (PgDip)",
"Phonetics (MSc)",
"Physical Activity for Health (MSC)",
"Physical Activity for Health (PgCert)",
"Physical Activity for Health (PgDip)",
"Playwriting (MSc)",
"Playwriting (MSc)",
"Policy Studies (MSc)",
"Policy Studies (MSc)",
"Primary Care Ophthalmology (Online Distance Learning) (MSc)",
"Primary Care Ophthalmology (Online Distance Learning) (Pg Cert)",
"Primary Care Ophthalmology (Online Distance Learning) (Pg Dip)",
"Primary Dental Care (Online Distance Learning) (MSc)",
"Primary Dental Care (Online Distance Learning) (PgCert)",
"Primary Dental Care (Online Distance Learning) (PgDip)",
"Product Design (MA (eca))",
"Professional Legal Practice (PgDip)",
"Professional Legal Practice (PgDip)",
"Prosthodontics (DClinDent)",
"Prosthodontics (MClinDent)",
"Psychological Research (MSc)",
"Psychological Research (MSc)",
"Psychology of Individual Differences (MSc)",
"Psychology of Individual Differences (MSc)",
"Psychology of Language (MSc)",
"Psychology of Language (MSc)",
"Psychology of Mental Health (Conversion) (MSc)",
"Psychotherapy and Counselling (DPsych)",
"Psychotherapy and Counselling (DPsych)",
"Psychotherapy and Counselling (DPsychotherapy)",
"Psychotherapy and Counselling (Interpersonal Dialogue) (DPsychotherapy)",
"Public Health (MPH) (Full Time)",
"Public Health (MPH) (Part Time)",
"Public Health (PGC) (Online Distance Learning)",
"Public Health (PGD) (Online Distance Learning)",
"Public Policy (PgCert)",
"Public Policy (PgCert)",
"Public Policy (PgDip)",
"Public Policy (PgDip)",
"Quantitative Genetics and Genome Analysis (MSc)",
"Quantitative Genetics and Genome Analysis (MSc)",
"Quantitative Genetics and Genome Analysis (PgDip)",
"Regenerative Medicine: Clinical and Industrial Delivery (MSc)",
"Religious Studies (MSc)",
"Religious Studies (MSc)",
"Renaissance and Early Modern Studies (MSc)",
"Renaissance and Early Modern Studies (MSc)",
"Science and Religion (MSc)",
"Science and Religion (MSc)",
"Science and Technology in Society (MSc)",
"Science and Technology in Society (MSc)",
"Science Communication and Public Engagement (MSc)",
"Science Communication and Public Engagement (MSc) (Online Distance Learning)",
"Science Communication and Public Engagement (PgCert) (Online Distance Learning)",
"Science Communication and Public Engagement (PgDip) (Online Distance Learning)",
"Science, Technology and International Development (MSc)",
"Science, Technology and International Development (MSc)",
"Scientific Computing (MSc)",
"Scottish Art and Visual Culture (MSc)",
"Scottish Art and Visual Culture (MSc)",
"Scottish Culture and Heritage (Online distance Learning) (PG Cert)",
"Scottish Culture and Heritage (Online Distance Learning) (PG Cert)",
"Scottish History (MSc)",
"Scottish History (MSc)",
"Sensor and Imaging Systems   (MSc)",
"Signal Processing and Communications (MSc)",
"Signal Processing and Communications (MSc)",
"Social Anthropology (MSc)",
"Social Anthropology (MSc)",
"Social Psychology (MSc)",
"Social Psychology (MSc)",
"Social Psychology (PgCert)",
"Social Psychology (PgDip)",
"Social Research (MSc)",
"Social Research (MSc)",
"Social Work (MSW)",
"Sociology and Global Change (MSc)",
"Sociology and Global Change (MSc)",
"Soils and Sustainability (SAC) (MSc)",
"Soils and Sustainability (SAC) (MSc)",
"Soils and Sustainability (SAC) (MSc)",
"Sound Design (MSc)",
"Sound Design (MSc)",
"Sound Environments (MSc)",
"Sound Environments (MSc)",
"Speech and Language Processing (MSc)",
"Speech and Language Processing (MSc)",
"Sport Policy, Management and International Development (MSC)",
"Statistics and Operational Research (MSc)",
"Statistics and Operational Research (MSc)",
"Statistics with Data Science (MSc)",
"Statistics with Data Science (MSc)",
"Statistics with Data Science (MSc)",
"Strength and Conditioning (MSc)",
"Strength and Conditioning (PgDip)",
"Structural and Fire Safety Engineering (MSc)",
"Surgical Sciences (Online Distance Learning) (MSc)",
"Sustainable Energy Systems (MSc)",
"Sustainable Energy Systems (PgDip)",
"Sustainable Plant Health (MSc) (SRUC)",
"Sustainable Plant Health (MSc) (SRUC)",
"Sustainable Plant Health (MSc) (SRUC)",
"Synthetic Biology and Biotechnology (MSc)",
"Synthetic Biology and Biotechnology (PGD)",
"Systems and Synthetic Biology (MSc)",
"Systems and Synthetic Biology (PgDip)",
"Teaching English to Speakers of Other Languages (MSc)",
"Teaching English to Speakers of Other Languages (PgDip)",
"Textiles (MFA)",
"Theatre and Performance Studies (MSc)",
"Theatre and Performance Studies (MSc)",
"Theology in History (MSc)",
"Theology in History (MSc)",
"Theology in History (MTh)",
"Theology in History (MTh)",
"Theoretical Physics MSc",
"Transfusion, Transplantation and Tissue Banking (MSc)",
"Translation Studies (MSc)",
"Translation Studies (MSc)",
"Trauma and Orthopaedics (Online Distance Learning) (ChM)",
"Urban Strategies and Design (MSC)",
"Urban Strategies and Design (MSC)",
"Urology (Online Distance Learning) (ChM)",
"Vascular and Endovascular Surgery (Online Distance Learning) (ChM)",
"World Christianity (MSc)",
"World Christianity (MSc)",
"World Christianity (MTh)",
"World Christianity (MTh)", ]
valuelist = ["26400",
"",
"20100",
"10500",
"19300",
"23700",
"20100",
"6435",
"6435",
"9650",
"19300",
"19300",
"9650",
"6435",
"19300",
"9650",
"",
"19300",
"9650",
"19300",
"9650",
"",
"",
"19300",
"9650",
"10050",
"20100",
"26400",
"27400",
"13700",
"27400",
"13700",
"17600",
"17600",
"8800",
"5870",
"20100",
"10050",
"19300",
"9650",
"20100",
"19300",
"9650",
"19300",
"9650",
"21850",
"19300",
"9650",
"20100",
"13700",
"27400",
"13700",
"9135",
"22800",
"19300",
"9650",
"19300",
"9650",
"27400",
"27400",
"27400",
"9135",
"27400",
"",
"",
"",
"27400",
"27400",
"27400",
"27400",
"19300",
"9650",
"27400",
"27400",
"21000",
"23700",
"7900",
"19300",
"",
"20100",
"10050",
"",
"",
"",
"19300",
"9650",
"19300",
"9650",
"9650",
"19300",
"",
"19300",
"19300",
"9650",
"19300",
"19300",
"9650",
"19300",
"9650",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"20100",
"10050",
"27400",
"13700",
"9135",
"19300",
"9650",
"19300",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"9650",
"19300",
"9650",
"20100",
"10500",
"20100",
"",
"",
"25500",
"12750",
"25500",
"12750",
"27400",
"13700",
"9135",
"",
"",
"",
"20100",
"10050",
"13700",
"20100",
"10050",
"19300",
"9650",
"19300",
"9650",
"17600",
"3500",
"3500",
"19300",
"9650",
"6435",
"3500",
"19300",
"19300",
"9650",
"19300",
"9650",
"19300",
"19300",
"9650",
"20100",
"19300",
"9650",
"9650",
"19300",
"12870",
"9650",
"19300",
"27400",
"13700",
"9135",
"",
"41300",
"20100",
"10050",
"27400",
"20100",
"27400",
"20100",
"10050",
"20100",
"10050",
"20100",
"10500",
"",
"",
"19300",
"9650",
"27400",
"27400",
"11850",
"7900",
"23700",
"19300",
"9650",
"25500",
"12750",
"8500",
"19300",
"9650",
"20100",
"10050",
"19300",
"9650",
"25500",
"12750",
"8500",
"19300",
"9650",
"6435",
"19300",
"9650",
"6435",
"19300",
"9650",
"6435",
"19300",
"9650",
"6435",
"19300",
"9650",
"6435",
"19300",
"9650",
"6435",
"19300",
"19300",
"9650",
"6435",
"19300",
"6435",
"12870",
"22800",
"23700",
"23700",
"11850",
"20100",
"10050",
"19300",
"9650",
"20100",
"25500",
"12750",
"8500",
"23700",
"11850",
"25500",
"12750",
"8500",
"25500",
"12750",
"8500",
"",
"",
"",
"",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"20100",
"10050",
"27400",
"13700",
"27400",
"13550",
"",
"13700",
"20100",
"13700",
"19300",
"9650",
"20100",
"10050",
"26400",
"23410",
"25500",
"12750",
"25500",
"25500",
"12750",
"8500",
"9650",
"",
"23700",
"11850",
"7900",
"23700",
"11850",
"7900",
"20100",
"13700",
"",
"",
"19300",
"9650",
"9650",
"",
"",
"",
"",
"19300",
"9650",
"19300",
"9650",
"",
"",
"",
"",
"19300",
"9650",
"6435",
"",
"19300",
"9650",
"",
"",
"",
"20100",
"13700",
"19300",
"9650",
"23700",
"7900",
"23700",
"11850",
"23700",
"7900",
"19300",
"9650",
"",
"20100",
"10050",
"23700",
"23700",
"20100",
"10050",
"27400",
"13700",
"27400",
"20100",
"20100",
"19300",
"9650",
"20100",
"13700",
"12870",
"12870",
"19300",
"9650",
"12870",
"6435",
"12870",
"27400",
"13700",
"9135",
"",
"",
"",
"",
"",
"19300",
"9650",
"",
"",
"",
"",
"",
"19300",
"9650",
"19300",
"9650",
"",
"",
"",
"",
"",
"19300",
"20100",
"",
"",
"",
"18400",
"9200",
"",
"",
"",
"",
"",
"",
"19300",
"22800",
"",
"",
"",
"",
"",
"9650",
"19300",
"",
"",
"",
"",
"19300",
"9650",
"20100",
"19300",
"9650",
"19300",
"19300",
"9650",
"18400",
"9200",
"9200",
"18400",
"19300",
"19300",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"13700",
"19300",
"9650",
"19300",
"19300",
"19300",
"9650",
"12870",
"6435",
"19300",
"9650",
"19300",
"9650",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"19300",
"19300",
"12870",
"10050",
"20100",
"19300",
"9650",
"19300",
"9650",
"21000",
"19300",
"9650",
"20100",
"10050",
"6700",
"20100",
"20100",
"",
"21900",
"20100",
"25500",
"19300",
"19300",
"9650",
"19300",
"9650",
"",
"",
"",
"",
"",
"25500",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"19300",
"19300",
"20100",
"10050",
"19300",
"9650",
"19300",
"9650",
"20100",
"10050",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"20100",
"10050",
"20100",
"20100",
"10050",
"20100",
"20100",
"10050",
"6700",
"20100",
"10050",
"20100",
"41300",
"41300",
"41300",
"41300",
"19300",
"12870",
"19300",
"12870",
"41300",
"41300",
"",
"",
"",
"23700",
"13700",
"19300",
"12870",
"19300",
"9650",
"19300",
"12870",
"20100",
"10050",
"",
"",
"20100",
"19300",
"6435",
"12870",
"19300",
"9650",
"19300",
"9650",
"",
"",
"",
"",
"",
"",
"20100",
"18400",
"9200",
"41300",
"41300",
"20100",
"10050",
"20100",
"10050",
"20100",
"10050",
"19300",
"17600",
"3500",
"3500",
"17600",
"19300",
"9650",
"",
"",
"7300",
"3650",
"14600",
"3650",
"27400",
"13700",
"27400",
"23700",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"19300",
"",
"",
"",
"19300",
"9650",
"19300",
"19300",
"9650",
"",
"",
"19300",
"9650",
"19500",
"23700",
"11850",
"19300",
"9650",
"20100",
"10050",
"6700",
"13400",
"19300",
"9650",
"19300",
"19300",
"9650",
"25500",
"12750",
"8500",
"20100",
"10050",
"19300",
"9650",
"23700",
"11850",
"19300",
"20100",
"10050",
"20100",
"10050",
"6700",
"19300",
"12870",
"23700",
"",
"23700",
"23700",
"25500",
"12750",
"8500",
"27400",
"27400",
"27400",
"27400",
"19300",
"12870",
"13700",
"19300",
"9650",
"19300",
"9650",
"19300",
"9650",
"19300",
"6435",
"19300",
"9650",
"",
"20100",
"10500",
"",
"",
"19300",
"9650",
"19300",
"9650",]
resultDict = {}
# print(len(list1))
# print(len(valuelist))
for i in range(len(list1)):
    resultDict[list1[i]] = valuelist[i]

# print(resultDict)

l = ["MEng                Aerospace Engineering  (H410) = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace/",
"BEng                Aerospace Engineering  (H405) = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/beng-aerospace-engineering/",
"MEng                Aerospace Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace-engineering-with-a-year-in-industry/",
"BSc                Accounting and Management  (NN42) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-accounting-management/",
"MEng                Aerospace Engineering with Study in Continental Europe  (H401) = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace-europe/",
"BSc                Accounting and Finance  (NN43) = http://www.bristol.ac.uk/study/undergraduate/2018/accounting-finance/bsc-accounting-finance/",
"BSc                Accounting and Finance with Study in Continental Europe  (NN34) = http://www.bristol.ac.uk/study/undergraduate/2018/accounting-finance/bsc-accounting-finance-europe/",
"BA                Ancient History  (V110) = http://www.bristol.ac.uk/study/undergraduate/2018/ancient-history/ba-ancient-history/",
"BA                Anthropology  (XD49) = http://www.bristol.ac.uk/study/undergraduate/2018/anthropology/ba-anthropology/",
"MArts                Anthropology with Innovation  (XD50) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-anthropology-with-innovation/",
"BSc                Applied Anatomy  (B112) = http://www.bristol.ac.uk/study/undergraduate/2018/anatomy/bsc-applied-anatomy/",
"BA                Archaeology and Anthropology  (VL46) = http://www.bristol.ac.uk/study/undergraduate/2018/anthropology/ba-arch-anth/",
"BSc                Biochemistry  (C700) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem/",
"MSci                Biochemistry  (C701) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/msci-biochemistry/",
"BSc                Biochemistry with Medical Biochemistry  (C720) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem-medical-biochem/",
"BSc                Biochemistry with Molecular Biology and Biotechnology  (C790) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem-molecular-biology-biotech/",
"BSc                Biochemistry with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem-industry/",
"MSci                Biology  (C103) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/msci-biology/",
"BSc                Biology  (C100) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/bsc-biology/",
"BSc                Cancer Biology and Immunology  (B131) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cancer-biology-immunology/",
"BSc                Cancer Biology and Immunology with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cancer-biology-and-immunology-with-study-in-i/",
"BSc                Cellular and Molecular Medicine  (B130) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cellular-molecular/",
"BSc                Cellular and Molecular Medicine with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cellular-and-molecular-medicine-with-study-in/",
"BSc                Chemical Physics  (F320) = http://www.bristol.ac.uk/study/undergraduate/2018/chemical-physics/bsc-chemical-physics/",
"MSci                Chemical Physics  (F322) = http://www.bristol.ac.uk/study/undergraduate/2018/chemical-physics/msci-chemical-physics/",
"MSci                Chemical Physics with Industrial Experience  (F323) = http://www.bristol.ac.uk/study/undergraduate/2018/chemical-physics/msci-chemical-physics-industry/",
"BSc                Chemistry  (F100) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/bsc-chemistry/",
"MSci                Chemistry  (F103) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry/",
"MEng                Aerospace Engineering with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace-study-abroad/",
"MSci                Chemistry with Industrial Experience  (F105) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry-industry/",
"MSci                Chemistry with Study Abroad  (F107) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry-study-abroad/",
"MSci                Chemistry with Study in Continental Europe  (F104) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry-europe/",
"BSc                Chemistry with a Preliminary Year of Study  (F108) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/bsc-chemistry-preliminary-study/",
"BSc                Childhood Studies  (L520) = http://www.bristol.ac.uk/study/undergraduate/2018/childhood-studies/bsc-childhood/",
"BSc                Childhood Studies with Management  (L524) = http://www.bristol.ac.uk/study/undergraduate/2018/childhood-studies/bsc-childhood-management/",
"BSc                Childhood Studies with Quantitative Research Methods  (L522) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-childhood-quantitative-research/",
"BSc                Childhood Studies with Study Abroad  (L525) = http://www.bristol.ac.uk/study/undergraduate/2018/childhood-studies/bsc-childhood-studies-with-study-abroad/",
"BEng                Civil Engineering  (H205) = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/beng-civil-eng/",
"MEng                Civil Engineering  (H200) = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-eng/",
"MEng                Civil Engineering with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-eng-study-abroad/",
"MEng                Civil Engineering with Study in Continental Europe  (H201) = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-eng-europe/",
"MEng                Civil Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-engineering-with-a-year-in-industry/",
"BA                Classical Studies  (Q810) = http://www.bristol.ac.uk/study/undergraduate/2018/classical-studies/ba-classical-studies/",
"BA                Classics  (Q800) = http://www.bristol.ac.uk/study/undergraduate/2018/classics/ba-classics/",
"BSc                Computer Science  (G400) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/bsc-comp-sci/",
"MEng                Computer Science  (G403) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/meng-comp-sci/",
"BEng                Computer Science and Electronics  (GH45) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/beng-computer-science-and-electronics/",
"MEng                Computer Science and Electronics with Study Abroad  (GH4P) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-comp-sci-electronics-study-abroad/",
"MEng                Computer Science and Electronics  (GH46) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-comp-sci-electronics/",
"MEng                Computer Science with Innovation  (G404) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/meng-computer-science-with-innovation/",
"MEng                Computer Science with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/meng-comp-sci-study-abroad/",
"MEng                Computer Science with Study in Continental Europe  (G401) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/meng-comp-sci-europe/",
"BA                Czech and French  (RR1V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-french/",
"BA                Czech and German  (RR2V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-german/",
"BA                Czech and Italian  (RR3V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-italian/",
"BA                Czech and Portuguese  (RR5V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-portuguese/",
"BA                Czech and Russian  (R701) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-russian/",
"BA                Czech and Spanish  (RR4V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-spanish/",
"Dip                Dental Hygiene = http://www.bristol.ac.uk/study/undergraduate/2018/dental-hygiene/dip-dental-hygiene/",
"Dip                Dental Therapy = http://www.bristol.ac.uk/study/undergraduate/2018/dental-therapy/dip-dental-therapy/",
"BDS                Dentistry  (A206) = http://www.bristol.ac.uk/study/undergraduate/2018/dentistry/bds-dentistry/",
"BSc                Economics  (L100) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ/",
"BSc                Economics and Accounting  (LN14) = http://www.bristol.ac.uk/study/undergraduate/2018/accounting-finance/bsc-econ-accounting/",
"BSc                Economics and Econometrics  (L140) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-econometrics/",
"BSc                Economics and Finance  (LN13) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-finance/",
"BSc                Economics and Management  (LN12) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-econ-management/",
"BSc                Economics and Mathematics  (LG11) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-maths/",
"BSc                Economics and Politics  (LL12) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-politics/",
"MSci                Childhood Studies with Quantitative Research Methods  (L523) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-childhood-quantitative-research/",
"BSc                Economics with Study in Continental Europe  (L101) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-europe/",
"BSc                Education Studies  (X300) = http://www.bristol.ac.uk/study/undergraduate/2018/education/bsc-education-studies/",
"BEng                Electrical and Electronic Engineering  (H600) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/beng-elec-electronic/",
"MEng                Electrical and Electronic Engineering  (H606) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-elec-electronic/",
"MEng                Electrical and Electronic Engineering with Innovation  (H604) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/meng-electrical-and-electronic-engineering-with-i/",
"MEng                Electrical and Electronic Engineering with Study in Continental Europe  (H605) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-elec-electronic-europe/",
"MEng                Electrical and Electronic Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-electrical-and-electronic-engineering-with-a/",
"BEng                Engineering Mathematics  (G162) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/beng-eng-maths/",
"MEng                Engineering Mathematics  (G161) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/meng-eng-maths/",
"MEng                Engineering Mathematics with Study Abroad  (G160) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/meng-maths-study-abroad/",
"MEng                Engineering Mathematics with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/meng-engineering-mathematics-with-a-year-in-indus/",
"BA                English  (Q300) = http://www.bristol.ac.uk/study/undergraduate/2018/english/ba-english/",
"BA                English and Classical Studies  (QQ38) = http://www.bristol.ac.uk/study/undergraduate/2018/english/ba-english-classical-studies/",
"BA                English and Philosophy  (QV35) = http://www.bristol.ac.uk/study/undergraduate/2018/english/ba-english-philosophy/",
"MEng                Engineering Design with Study in Industry  (H150) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-design/meng-eng-design-industry/",
"BSc                Environmental Geoscience  (F640) = http://www.bristol.ac.uk/study/undergraduate/2018/geoscience/bsc-environmental-geoscience/",
"MSci                Environmental Geoscience with Study Abroad  (F644) = http://www.bristol.ac.uk/study/undergraduate/2018/geoscience/msci-environmental-geoscience-study-abroad/",
"BA                Film and English  (6T3X) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-english/",
"BA                Film and French  (2LK6) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-french/",
"BA                Film and German  (4F29) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-german/",
"BA                Film and Italian  (4L92) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-italian/",
"BA                Film and Spanish  (L288) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-spanish/",
"BA                Film and Television  (4M5N) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-television/",
"MArts                Film and Television with Innovation  (4M50) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-film-and-television-with-innovation/",
"BA                French  (R100) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french/",
"BA                French and German  (RR12) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-german/",
"BA                French and Italian  (RR13) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-italian/",
"BA                Film and Portuguese  (4PP8) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-portuguese/",
"BA                French and Portuguese  (RR15) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-portuguese/",
"BA                French and Russian  (RR17) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-russian/",
"BA                French and Spanish  (RR14) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-spanish/",
"BSc                Geography  (F800) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/bsc-geography/",
"MSci                Geography  (F803) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/msci-geography/",
"MSci                Geography with Innovation  (F805) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-geography-with-innovation/",
"MSci                Geography with Quantitative Research Methods  (F804) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-geography-quantitative-research/",
"BSc                Geography with Study Abroad  (09F4) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/bsc-study-abroad/",
"BSc                Geography with Study in Continental Europe  (F801) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/bsc-geography-study-europe/",
"BSc                Geology  (F600) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/bsc-geology/",
"MSci                Geology  (F603) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/msci-geology/",
"BSc                Geology and Biology  (FC61) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/bsc-geology-biology/",
"MSci                Geology with Study Abroad  (F609) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/msci-geology-study-abroad/",
"BSc                Geophysics  (F661) = http://www.bristol.ac.uk/study/undergraduate/2018/geophysics/bsc-geophysics/",
"MSci                Geophysics  (F662) = http://www.bristol.ac.uk/study/undergraduate/2018/geophysics/msci-geophysics/",
"MSci                Geophysics with Study Abroad  (F663) = http://www.bristol.ac.uk/study/undergraduate/2018/geophysics/msci-geophysics-with-study-abroad/",
"BA                German  (R200) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german/",
"BSc                Geography with Quantitative Research Methods  (F802) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-geography-quantitative-research/",
"BA                German and Italian  (RR23) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-italian/",
"BA                German and Portuguese  (RR25) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-portuguese/",
"BA                German and Russian  (RR27) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-russian/",
"BA                German and Spanish  (RR24) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-spanish/",
"BA                Hispanic Studies  (RR45) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-hispanic-studies/",
"BA                History  (V100) = http://www.bristol.ac.uk/study/undergraduate/2018/history/ba-history/",
"BA                History of Art and German  (VR32) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-german/",
"MSci                Environmental Geoscience  (F641) = http://www.bristol.ac.uk/study/undergraduate/2018/geoscience/msci-environmental-geoscience/",
"BA                History of Art and Italian  (VR33) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-italian/",
"BA                History of Art and Portuguese  (VR35) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-portuguese/",
"BA                History of Art and Russian  (VR37) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-russian/",
"BA                History of Art and Spanish  (VR34) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-spanish/",
"MArts                History with Innovation  (V104) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-history-with-innovation/",
"BSc                International Business Management with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-international-business-management-with-study-/",
"Cert                International Foundation Programme (Arts and Humanities) = http://www.bristol.ac.uk/study/undergraduate/2018/foundation/english-arts-humanities/",
"Cert                International Foundation Programme (Science, Technology, Engineering and Mathematics) = http://www.bristol.ac.uk/study/undergraduate/2018/foundation/english-stem/",
"Cert                International Foundation Programme (Social Sciences and Law) = http://www.bristol.ac.uk/study/undergraduate/2018/foundation/english-ssl/",
"BA                Italian  (R310) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian/",
"BSc                International Business Management  (N120) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-international-business-management/",
"BA                Italian and Portuguese  (RR35) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian-portuguese/",
"BA                Italian and Russian  (RR37) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian-russian/",
"BA                Italian and Spanish  (RR34) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian-spanish/",
"LLB                Law  (M100) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law/",
"LLB                Law and French  (MR11) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-french/",
"LLB                Law and Spanish  (MR13) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-and-spanish/",
"LLB                Law with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-study-abroad/",
"LLB                Law with Study in Continental Europe = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-europe/",
"BA                Liberal Arts  (2ZB7) = http://www.bristol.ac.uk/study/undergraduate/2018/liberal-arts/ba-liberal-arts/",
"MLibArts                Liberal Arts with Study Abroad  (2T23) = http://www.bristol.ac.uk/study/undergraduate/2018/liberal-arts/mlibarts-liberal-arts-study-abroad/",
"LLB                Law and German  (MR12) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-german/",
"BSc                Management  (N200) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-management/",
"MSci                Management with Innovation  (N204) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-management-with-innovation/",
"BA                History of Art and French  (VR31) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-french/",
"BSc                Management with Study in Continental Europe  (4H56) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-management-europe/",
"BSc                Mathematics  (G100) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths/",
"MSci                Mathematics  (G103) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths/",
"BSc                Mathematics and Philosophy  (VG51) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-philosophy/",
"MSci                Mathematics and Philosophy  (GV15) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-philosophy/",
"BA                History of Art   (V350) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art/",
"MSci                Mathematics and Physics  (GFC3) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-physics/",
"BSc                Mathematics with Statistics  (G1G3) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-statistics/",
"MSci                Mathematics with Statistics  (G1GH) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-statistics/",
"BSc                Mathematics and Computer Science  (GG14) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/bsc-maths-comp-sci/",
"MSci                Mathematics with Study Abroad  (G105) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-mathematics-with-study-abroad/",
"BSc                Mathematics and Physics  (GFD3) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-physics/",
"BSc                Mathematics with Study in Continental Europe  (G101) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-europe/",
"BEng                Mechanical Engineering  (H305) = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/beng-mech-eng/",
"MEng                Mechanical Engineering  (H300) = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mech-eng/",
"MEng                Mechanical Engineering with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mech-eng-study-abroad/",
"MEng                Mechanical Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mechanical-engineering-with-a-year-in-indust/",
"MEng                Mechanical and Electrical Engineering  (H360) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-mechanical-and-electrical-engineering/",
"MEng                Mechanical and Electrical Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-mechanical-and-electrical-engineering-with-a/",
"BSc                Medical Microbiology  (C521) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-medical-microbiology/",
"BSc                Medical Microbiology with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-medical-microbiology-with-study-in-industry/",
"MEng                Mechanical Engineering with Study in Continental Europe  (H301) = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mech-eng-europe/",
"BEng                Mechanical and Electrical Engineering  (H361) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/beng-mechanical-and-electrical-engineering/",
"MB ChB                Medicine  (A100) = http://www.bristol.ac.uk/study/undergraduate/2018/medicine/mb-medicine/",
"BA                Modern Languages  (RR01) = http://www.bristol.ac.uk/study/undergraduate/2018/modern-languages/ba-modern-languages/",
"MSci                Mathematics with Study in Continental Europe  (G104) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-europe/",
"BA                Music  (W300) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music/",
"BA                Music and French  (WR31) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music-french/",
"BA                Music and German  (WR32) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music-german/",
"MSci                Neuroscience with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/neuroscience/msci-neuroscience-industry/",
"MSci                Palaeontology and Evolution  (CF16) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/msci-palaentology-evolution/",
"BSc                Pharmacology  (B210) = http://www.bristol.ac.uk/study/undergraduate/2018/pharmacology/bsc-pharmacology/",
"BA                Music and Italian  (WR33) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music-italian/",
"MSci                Pharmacology with Study in Industry  (B211) = http://www.bristol.ac.uk/study/undergraduate/2018/pharmacology/msci-pharmacology-industry/",
"MArts                Music with Innovation  (W304) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-music-with-innovation/",
"BA                Philosophy  (V500) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy/",
"BSc                Palaeontology and Evolution  (CF17) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/bsc-palaeontology-and-evolution/",
"BSc                Philosophy and Economics  (VL51) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/bsc-philosophy-econ/",
"BA                Philosophy and French  (RV15) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-french/",
"BA                Philosophy and Italian  (RV35) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-italian/",
"BA                Philosophy and Portuguese  (RV55) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-portuguese/",
"BA                Philosophy and Spanish  (RV45) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-spanish/",
"BSc                Philosophy and Politics  (VL52) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-philosophy-politics/",
"BA                Philosophy and Theology  (VV56) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-theology/",
"MSci                Physics  (F303) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics/",
"BSc                Physics  (F300) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics/",
"BA                Philosophy and Russian  (RV75) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-russian/",
"BSc                Physics and Philosophy  (FV35) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics-philosophy/",
"BSc                Physics with Astrophysics  (F3F5) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics-astrophysics/",
"MSci                Physics with Astrophysics  (F3FM) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-astrophysics/",
"MSci                Physics with Industrial Experience  (F305) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-industry/",
"MSci                Physics and Philosophy  (FVH5) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-philosophy/",
"MSci                Physics with Study in Continental Europe  (F304) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-europe/",
"BSc                Physics with a Preliminary Year of Study  (F308) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics-preliminary-study/",
"BSc                Physiological Science  (B120) = http://www.bristol.ac.uk/study/undergraduate/2018/physiology/bsc-physiology-science/",
"MSci                Physiological Science with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/physiology/msci-physiological-science-industry/",
"BSc                Neuroscience  (B140) = http://www.bristol.ac.uk/study/undergraduate/2018/neuroscience/bsc-neuroscience/",
"BA                Politics and French  (RL12) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-french/",
"BA                Politics and German  (RL22) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-german/",
"MSci                Physics with Innovation  (F306) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-physics-with-innovation/",
"BSc                Politics and International Relations  (L200) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-politics-international-relations/",
"BSc                Politics and International Relations with Study Abroad  (L201) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-politics-and-international-relations-with-stu/",
"BA                Politics and Portuguese  (RL52) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-portuguese/",
"BA                Politics and Russian  (RL72) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-russian/",
"BA                Politics and Spanish  (RL42) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-spanish/",
"BA                Politics and Italian  (RL32) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-italian/",
"BSc                Politics with Quantitative Research Methods  (L202) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-politics-quantitative-research/",
"MSci                Politics with Quantitative Research Methods  (L203) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-politics-quantitative-research/",
"BSc                Politics with Quantitative Research Methods with Study Abroad  (L204) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-politics-with-quantitative-research-methods-w/",
"BSc                Psychology  (C801) = http://www.bristol.ac.uk/study/undergraduate/2018/psychology/bsc-psychology/",
"BSc                Psychology in Education  (X301) = http://www.bristol.ac.uk/study/undergraduate/2018/education/bsc-psychology-in-education/",
"MSci                Psychology with Innovation  (C804) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-psychology-with-innovation/",
"BA                Religion and Theology  (V600) = http://www.bristol.ac.uk/study/undergraduate/2018/religion-theology/ba-religion-theology/",
"MArts                Religion and Theology with Study Abroad  (V601) = http://www.bristol.ac.uk/study/undergraduate/2018/religion-theology/marts-religion-and-theology-with-study-abroad/",
"MSci                Psychology  (C802) = http://www.bristol.ac.uk/study/undergraduate/2018/psychology/msci-psychology/",
"BA                Russian  (R700) = http://www.bristol.ac.uk/study/undergraduate/2018/russian/ba-russian/",
"MSci                Physics with International Experience  (F307) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-with-international-experience/",
"BA                Russian and Portuguese  (RR57) = http://www.bristol.ac.uk/study/undergraduate/2018/russian/ba-russian-portuguese/",
"BSc                Social Policy  (L400) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy/",
"BSc                Social Policy and Politics  (LL42) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-politics/",
"BSc                Social Policy with Criminology  (LM49) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-with-criminology/",
"BSc                Social Policy with Quantitative Research Methods  (L402) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-social-policy-quantitative-research/",
"MSci                Social Policy with Quantitative Research Methods  (L403) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-social-policy-quantitative-research/",
"BSc                Social Policy and Sociology  (LL43) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-sociology/",
"BSc                Social Policy with Study Abroad  (L404) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-with-study-abroad/",
"BSc                Sociology  (L300) = http://www.bristol.ac.uk/study/undergraduate/2018/sociology/bsc-sociology/",
"BSc                Social Policy with Management  (LN42) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-management/",
"BSc                Sociology and Philosophy  (LV35) = http://www.bristol.ac.uk/study/undergraduate/2018/sociology/bsc-sociology-philosophy/",
"BSc                Sociology with Quantitative Research Methods  (L302) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-sociology-quantitative-research/",
"BSc                Sociology with Quantitative Research Methods with Study Abroad  (L304) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-sociology-with-quantitative-research-methods-/",
"BSc                Sociology with Study Abroad  (L301) = http://www.bristol.ac.uk/study/undergraduate/2018/sociology/bsc-sociology-study-abroad/",
"BSc                Politics and Sociology  (LL23) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-politics-sociology/",
"BA                Spanish and Portuguese  (RR54) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-spanish-portuguese/",
"MSci                Sociology with Quantitative Research Methods  (L303) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-sociology-quantitative-research/",
"BA                Spanish and Russian  (RR47) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-spanish-russian/",
"BA                Theatre and English  (4CC8) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-english/",
"BA                Theatre and Film  (4KDU) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-film/",
"BA                Spanish  (R400) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-spanish/",
"BA                Theatre and German  (21C7) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-german/",
"BA                Theatre and Performance Studies  (2Q3W) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-performance/",
"BA                Theatre and Portuguese  (R2D8) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-portuguese/",
"BA                Theatre and Spanish  (4D8C) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-spanish/",
"BA                Theatre and Italian  (22FF) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-italian/",
"BA                Theology and Sociology  (VL63) = http://www.bristol.ac.uk/study/undergraduate/2018/religion-theology/ba-theology-sociology/",
"MSci                Theoretical Physics  (F340) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-theoretical-physics/",
"BSc                Veterinary Nursing and Bioveterinary Science  (DC37) = http://www.bristol.ac.uk/study/undergraduate/2018/vet-nursing-biovet-science/bsc-vet-nursing/",
"MArts                Theatre with Innovation  (2Q50) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-theatre-with-innovation/",
"BVSc                Veterinary Science  (D100) = http://www.bristol.ac.uk/study/undergraduate/2018/vet-science/bvsc-veterinary-science/",
"BA                Theatre and French  (W43F) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-french/",
"BSc                Virology and Immunology  (C540) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-virology-immunology/",
"BSc                Virology and Immunology with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-virology-and-immunology-with-study-in-industry/",
"BSc                Zoology  (C300) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/bsc-zoology/",
"MSci                Zoology  (C303) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/msci-zoology/",
"BA                Philosophy and German  (RV25) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-german/", ]
l = list(set(l))
p = []
d = []
for i in l:
    p.append(i.split('=')[0])
    d.append(i.split('=')[1])
# print(p)
# print(len(p))
# print(d)
# print(len(d))