list1 = ["Anthropology",
"APEX",
"Aquatic Resources",
"Art",
"Biology",
"Business Administration",
"Catholic Studies",
"Celtic Studies",
"Chemistry",
"Classics",
"Computer Science",
"Co-operative Education",
"Development Studies",
"Earth Sciences",
"Economics",
"Engineering",
"English",
"Environmental Sciences",
"French",
"German",
"Health",
"History",
"Human Kinetics",
"Human Nutrition",
"Interdisciplinary Studies",
"Mathematics",
"Mi'kmaq",
"Music",
"Nursing",
"Philosophy",
"Physics",
"Political Science",
"Psychology",
"Public Policy and Governance",
"Religious Studies",
"Sociology",
"Spanish",
"Statistics",
"Women's & Gender Studies", ]
valuelist = ["https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ANTH&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=APEX&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=AQUA&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ART&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=BIOL&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=BSAD&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=CATH&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=CELT&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=CHEM&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=CLAS&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=CSCI&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=COOP&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=DEVS&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ESCI&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ECON&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ENGR&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ENGL&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=ENSC&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=FREN&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=GERM&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=HLTH&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=HIST&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=HKIN&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=HNU&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=IDS&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=MATH&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=MIKM&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=MUSI&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=NURS&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=PHIL&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=PHYS&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=PSCI&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=PSYC&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=PGOV&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=RELS&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=SOCI&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=SPAN&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=STAT&pterm=201810",
"https://mesamis.stfx.ca/reports/Timetable_List.asp?pdept=WMGS&pterm=201810", ]
resultDict = {}
print(len(list1))
print(len(valuelist))
for i in range(len(list1)):
    resultDict[list1[i]] = valuelist[i]

print(resultDict)

l = ["MEng                Aerospace Engineering  (H410) = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace/",
"BEng                Aerospace Engineering  (H405) = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/beng-aerospace-engineering/",
"MEng                Aerospace Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace-engineering-with-a-year-in-industry/",
"BSc                Accounting and Management  (NN42) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-accounting-management/",
"MEng                Aerospace Engineering with Study in Continental Europe  (H401) = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace-europe/",
"BSc                Accounting and Finance  (NN43) = http://www.bristol.ac.uk/study/undergraduate/2018/accounting-finance/bsc-accounting-finance/",
"BSc                Accounting and Finance with Study in Continental Europe  (NN34) = http://www.bristol.ac.uk/study/undergraduate/2018/accounting-finance/bsc-accounting-finance-europe/",
"BA                Ancient History  (V110) = http://www.bristol.ac.uk/study/undergraduate/2018/ancient-history/ba-ancient-history/",
"BA                Anthropology  (XD49) = http://www.bristol.ac.uk/study/undergraduate/2018/anthropology/ba-anthropology/",
"MArts                Anthropology with Innovation  (XD50) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-anthropology-with-innovation/",
"BSc                Applied Anatomy  (B112) = http://www.bristol.ac.uk/study/undergraduate/2018/anatomy/bsc-applied-anatomy/",
"BA                Archaeology and Anthropology  (VL46) = http://www.bristol.ac.uk/study/undergraduate/2018/anthropology/ba-arch-anth/",
"BSc                Biochemistry  (C700) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem/",
"MSci                Biochemistry  (C701) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/msci-biochemistry/",
"BSc                Biochemistry with Medical Biochemistry  (C720) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem-medical-biochem/",
"BSc                Biochemistry with Molecular Biology and Biotechnology  (C790) = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem-molecular-biology-biotech/",
"BSc                Biochemistry with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/biochemistry/bsc-biochem-industry/",
"MSci                Biology  (C103) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/msci-biology/",
"BSc                Biology  (C100) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/bsc-biology/",
"BSc                Cancer Biology and Immunology  (B131) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cancer-biology-immunology/",
"BSc                Cancer Biology and Immunology with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cancer-biology-and-immunology-with-study-in-i/",
"BSc                Cellular and Molecular Medicine  (B130) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cellular-molecular/",
"BSc                Cellular and Molecular Medicine with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-cellular-and-molecular-medicine-with-study-in/",
"BSc                Chemical Physics  (F320) = http://www.bristol.ac.uk/study/undergraduate/2018/chemical-physics/bsc-chemical-physics/",
"MSci                Chemical Physics  (F322) = http://www.bristol.ac.uk/study/undergraduate/2018/chemical-physics/msci-chemical-physics/",
"MSci                Chemical Physics with Industrial Experience  (F323) = http://www.bristol.ac.uk/study/undergraduate/2018/chemical-physics/msci-chemical-physics-industry/",
"BSc                Chemistry  (F100) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/bsc-chemistry/",
"MSci                Chemistry  (F103) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry/",
"MEng                Aerospace Engineering with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/aerospace/meng-aerospace-study-abroad/",
"MSci                Chemistry with Industrial Experience  (F105) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry-industry/",
"MSci                Chemistry with Study Abroad  (F107) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry-study-abroad/",
"MSci                Chemistry with Study in Continental Europe  (F104) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/msci-chemistry-europe/",
"BSc                Chemistry with a Preliminary Year of Study  (F108) = http://www.bristol.ac.uk/study/undergraduate/2018/chemistry/bsc-chemistry-preliminary-study/",
"BSc                Childhood Studies  (L520) = http://www.bristol.ac.uk/study/undergraduate/2018/childhood-studies/bsc-childhood/",
"BSc                Childhood Studies with Management  (L524) = http://www.bristol.ac.uk/study/undergraduate/2018/childhood-studies/bsc-childhood-management/",
"BSc                Childhood Studies with Quantitative Research Methods  (L522) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-childhood-quantitative-research/",
"BSc                Childhood Studies with Study Abroad  (L525) = http://www.bristol.ac.uk/study/undergraduate/2018/childhood-studies/bsc-childhood-studies-with-study-abroad/",
"BEng                Civil Engineering  (H205) = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/beng-civil-eng/",
"MEng                Civil Engineering  (H200) = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-eng/",
"MEng                Civil Engineering with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-eng-study-abroad/",
"MEng                Civil Engineering with Study in Continental Europe  (H201) = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-eng-europe/",
"MEng                Civil Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/civil-engineering/meng-civil-engineering-with-a-year-in-industry/",
"BA                Classical Studies  (Q810) = http://www.bristol.ac.uk/study/undergraduate/2018/classical-studies/ba-classical-studies/",
"BA                Classics  (Q800) = http://www.bristol.ac.uk/study/undergraduate/2018/classics/ba-classics/",
"BSc                Computer Science  (G400) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/bsc-comp-sci/",
"MEng                Computer Science  (G403) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/meng-comp-sci/",
"BEng                Computer Science and Electronics  (GH45) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/beng-computer-science-and-electronics/",
"MEng                Computer Science and Electronics with Study Abroad  (GH4P) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-comp-sci-electronics-study-abroad/",
"MEng                Computer Science and Electronics  (GH46) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-comp-sci-electronics/",
"MEng                Computer Science with Innovation  (G404) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/meng-computer-science-with-innovation/",
"MEng                Computer Science with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/meng-comp-sci-study-abroad/",
"MEng                Computer Science with Study in Continental Europe  (G401) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/meng-comp-sci-europe/",
"BA                Czech and French  (RR1V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-french/",
"BA                Czech and German  (RR2V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-german/",
"BA                Czech and Italian  (RR3V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-italian/",
"BA                Czech and Portuguese  (RR5V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-portuguese/",
"BA                Czech and Russian  (R701) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-russian/",
"BA                Czech and Spanish  (RR4V) = http://www.bristol.ac.uk/study/undergraduate/2018/czech/ba-czech-spanish/",
"Dip                Dental Hygiene = http://www.bristol.ac.uk/study/undergraduate/2018/dental-hygiene/dip-dental-hygiene/",
"Dip                Dental Therapy = http://www.bristol.ac.uk/study/undergraduate/2018/dental-therapy/dip-dental-therapy/",
"BDS                Dentistry  (A206) = http://www.bristol.ac.uk/study/undergraduate/2018/dentistry/bds-dentistry/",
"BSc                Economics  (L100) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ/",
"BSc                Economics and Accounting  (LN14) = http://www.bristol.ac.uk/study/undergraduate/2018/accounting-finance/bsc-econ-accounting/",
"BSc                Economics and Econometrics  (L140) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-econometrics/",
"BSc                Economics and Finance  (LN13) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-finance/",
"BSc                Economics and Management  (LN12) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-econ-management/",
"BSc                Economics and Mathematics  (LG11) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-maths/",
"BSc                Economics and Politics  (LL12) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-politics/",
"MSci                Childhood Studies with Quantitative Research Methods  (L523) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-childhood-quantitative-research/",
"BSc                Economics with Study in Continental Europe  (L101) = http://www.bristol.ac.uk/study/undergraduate/2018/economics/bsc-econ-europe/",
"BSc                Education Studies  (X300) = http://www.bristol.ac.uk/study/undergraduate/2018/education/bsc-education-studies/",
"BEng                Electrical and Electronic Engineering  (H600) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/beng-elec-electronic/",
"MEng                Electrical and Electronic Engineering  (H606) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-elec-electronic/",
"MEng                Electrical and Electronic Engineering with Innovation  (H604) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/meng-electrical-and-electronic-engineering-with-i/",
"MEng                Electrical and Electronic Engineering with Study in Continental Europe  (H605) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-elec-electronic-europe/",
"MEng                Electrical and Electronic Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-electrical-and-electronic-engineering-with-a/",
"BEng                Engineering Mathematics  (G162) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/beng-eng-maths/",
"MEng                Engineering Mathematics  (G161) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/meng-eng-maths/",
"MEng                Engineering Mathematics with Study Abroad  (G160) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/meng-maths-study-abroad/",
"MEng                Engineering Mathematics with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-maths/meng-engineering-mathematics-with-a-year-in-indus/",
"BA                English  (Q300) = http://www.bristol.ac.uk/study/undergraduate/2018/english/ba-english/",
"BA                English and Classical Studies  (QQ38) = http://www.bristol.ac.uk/study/undergraduate/2018/english/ba-english-classical-studies/",
"BA                English and Philosophy  (QV35) = http://www.bristol.ac.uk/study/undergraduate/2018/english/ba-english-philosophy/",
"MEng                Engineering Design with Study in Industry  (H150) = http://www.bristol.ac.uk/study/undergraduate/2018/engineering-design/meng-eng-design-industry/",
"BSc                Environmental Geoscience  (F640) = http://www.bristol.ac.uk/study/undergraduate/2018/geoscience/bsc-environmental-geoscience/",
"MSci                Environmental Geoscience with Study Abroad  (F644) = http://www.bristol.ac.uk/study/undergraduate/2018/geoscience/msci-environmental-geoscience-study-abroad/",
"BA                Film and English  (6T3X) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-english/",
"BA                Film and French  (2LK6) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-french/",
"BA                Film and German  (4F29) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-german/",
"BA                Film and Italian  (4L92) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-italian/",
"BA                Film and Spanish  (L288) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-spanish/",
"BA                Film and Television  (4M5N) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-television/",
"MArts                Film and Television with Innovation  (4M50) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-film-and-television-with-innovation/",
"BA                French  (R100) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french/",
"BA                French and German  (RR12) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-german/",
"BA                French and Italian  (RR13) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-italian/",
"BA                Film and Portuguese  (4PP8) = http://www.bristol.ac.uk/study/undergraduate/2018/film-television/ba-film-portuguese/",
"BA                French and Portuguese  (RR15) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-portuguese/",
"BA                French and Russian  (RR17) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-russian/",
"BA                French and Spanish  (RR14) = http://www.bristol.ac.uk/study/undergraduate/2018/french/ba-french-spanish/",
"BSc                Geography  (F800) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/bsc-geography/",
"MSci                Geography  (F803) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/msci-geography/",
"MSci                Geography with Innovation  (F805) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-geography-with-innovation/",
"MSci                Geography with Quantitative Research Methods  (F804) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-geography-quantitative-research/",
"BSc                Geography with Study Abroad  (09F4) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/bsc-study-abroad/",
"BSc                Geography with Study in Continental Europe  (F801) = http://www.bristol.ac.uk/study/undergraduate/2018/geography/bsc-geography-study-europe/",
"BSc                Geology  (F600) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/bsc-geology/",
"MSci                Geology  (F603) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/msci-geology/",
"BSc                Geology and Biology  (FC61) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/bsc-geology-biology/",
"MSci                Geology with Study Abroad  (F609) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/msci-geology-study-abroad/",
"BSc                Geophysics  (F661) = http://www.bristol.ac.uk/study/undergraduate/2018/geophysics/bsc-geophysics/",
"MSci                Geophysics  (F662) = http://www.bristol.ac.uk/study/undergraduate/2018/geophysics/msci-geophysics/",
"MSci                Geophysics with Study Abroad  (F663) = http://www.bristol.ac.uk/study/undergraduate/2018/geophysics/msci-geophysics-with-study-abroad/",
"BA                German  (R200) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german/",
"BSc                Geography with Quantitative Research Methods  (F802) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-geography-quantitative-research/",
"BA                German and Italian  (RR23) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-italian/",
"BA                German and Portuguese  (RR25) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-portuguese/",
"BA                German and Russian  (RR27) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-russian/",
"BA                German and Spanish  (RR24) = http://www.bristol.ac.uk/study/undergraduate/2018/german/ba-german-spanish/",
"BA                Hispanic Studies  (RR45) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-hispanic-studies/",
"BA                History  (V100) = http://www.bristol.ac.uk/study/undergraduate/2018/history/ba-history/",
"BA                History of Art and German  (VR32) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-german/",
"MSci                Environmental Geoscience  (F641) = http://www.bristol.ac.uk/study/undergraduate/2018/geoscience/msci-environmental-geoscience/",
"BA                History of Art and Italian  (VR33) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-italian/",
"BA                History of Art and Portuguese  (VR35) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-portuguese/",
"BA                History of Art and Russian  (VR37) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-russian/",
"BA                History of Art and Spanish  (VR34) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-spanish/",
"MArts                History with Innovation  (V104) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-history-with-innovation/",
"BSc                International Business Management with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-international-business-management-with-study-/",
"Cert                International Foundation Programme (Arts and Humanities) = http://www.bristol.ac.uk/study/undergraduate/2018/foundation/english-arts-humanities/",
"Cert                International Foundation Programme (Science, Technology, Engineering and Mathematics) = http://www.bristol.ac.uk/study/undergraduate/2018/foundation/english-stem/",
"Cert                International Foundation Programme (Social Sciences and Law) = http://www.bristol.ac.uk/study/undergraduate/2018/foundation/english-ssl/",
"BA                Italian  (R310) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian/",
"BSc                International Business Management  (N120) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-international-business-management/",
"BA                Italian and Portuguese  (RR35) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian-portuguese/",
"BA                Italian and Russian  (RR37) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian-russian/",
"BA                Italian and Spanish  (RR34) = http://www.bristol.ac.uk/study/undergraduate/2018/italian/ba-italian-spanish/",
"LLB                Law  (M100) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law/",
"LLB                Law and French  (MR11) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-french/",
"LLB                Law and Spanish  (MR13) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-and-spanish/",
"LLB                Law with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-study-abroad/",
"LLB                Law with Study in Continental Europe = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-europe/",
"BA                Liberal Arts  (2ZB7) = http://www.bristol.ac.uk/study/undergraduate/2018/liberal-arts/ba-liberal-arts/",
"MLibArts                Liberal Arts with Study Abroad  (2T23) = http://www.bristol.ac.uk/study/undergraduate/2018/liberal-arts/mlibarts-liberal-arts-study-abroad/",
"LLB                Law and German  (MR12) = http://www.bristol.ac.uk/study/undergraduate/2018/law/llb-law-german/",
"BSc                Management  (N200) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-management/",
"MSci                Management with Innovation  (N204) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-management-with-innovation/",
"BA                History of Art and French  (VR31) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art-french/",
"BSc                Management with Study in Continental Europe  (4H56) = http://www.bristol.ac.uk/study/undergraduate/2018/management/bsc-management-europe/",
"BSc                Mathematics  (G100) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths/",
"MSci                Mathematics  (G103) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths/",
"BSc                Mathematics and Philosophy  (VG51) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-philosophy/",
"MSci                Mathematics and Philosophy  (GV15) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-philosophy/",
"BA                History of Art   (V350) = http://www.bristol.ac.uk/study/undergraduate/2018/history-art/ba-history-art/",
"MSci                Mathematics and Physics  (GFC3) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-physics/",
"BSc                Mathematics with Statistics  (G1G3) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-statistics/",
"MSci                Mathematics with Statistics  (G1GH) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-statistics/",
"BSc                Mathematics and Computer Science  (GG14) = http://www.bristol.ac.uk/study/undergraduate/2018/computer-science/bsc-maths-comp-sci/",
"MSci                Mathematics with Study Abroad  (G105) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-mathematics-with-study-abroad/",
"BSc                Mathematics and Physics  (GFD3) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-physics/",
"BSc                Mathematics with Study in Continental Europe  (G101) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/bsc-maths-europe/",
"BEng                Mechanical Engineering  (H305) = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/beng-mech-eng/",
"MEng                Mechanical Engineering  (H300) = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mech-eng/",
"MEng                Mechanical Engineering with Study Abroad = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mech-eng-study-abroad/",
"MEng                Mechanical Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mechanical-engineering-with-a-year-in-indust/",
"MEng                Mechanical and Electrical Engineering  (H360) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-mechanical-and-electrical-engineering/",
"MEng                Mechanical and Electrical Engineering with a Year in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/meng-mechanical-and-electrical-engineering-with-a/",
"BSc                Medical Microbiology  (C521) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-medical-microbiology/",
"BSc                Medical Microbiology with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-medical-microbiology-with-study-in-industry/",
"MEng                Mechanical Engineering with Study in Continental Europe  (H301) = http://www.bristol.ac.uk/study/undergraduate/2018/mechanical-engineering/meng-mech-eng-europe/",
"BEng                Mechanical and Electrical Engineering  (H361) = http://www.bristol.ac.uk/study/undergraduate/2018/electrical-electronic-eng/beng-mechanical-and-electrical-engineering/",
"MB ChB                Medicine  (A100) = http://www.bristol.ac.uk/study/undergraduate/2018/medicine/mb-medicine/",
"BA                Modern Languages  (RR01) = http://www.bristol.ac.uk/study/undergraduate/2018/modern-languages/ba-modern-languages/",
"MSci                Mathematics with Study in Continental Europe  (G104) = http://www.bristol.ac.uk/study/undergraduate/2018/maths/msci-maths-europe/",
"BA                Music  (W300) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music/",
"BA                Music and French  (WR31) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music-french/",
"BA                Music and German  (WR32) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music-german/",
"MSci                Neuroscience with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/neuroscience/msci-neuroscience-industry/",
"MSci                Palaeontology and Evolution  (CF16) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/msci-palaentology-evolution/",
"BSc                Pharmacology  (B210) = http://www.bristol.ac.uk/study/undergraduate/2018/pharmacology/bsc-pharmacology/",
"BA                Music and Italian  (WR33) = http://www.bristol.ac.uk/study/undergraduate/2018/music/ba-music-italian/",
"MSci                Pharmacology with Study in Industry  (B211) = http://www.bristol.ac.uk/study/undergraduate/2018/pharmacology/msci-pharmacology-industry/",
"MArts                Music with Innovation  (W304) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-music-with-innovation/",
"BA                Philosophy  (V500) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy/",
"BSc                Palaeontology and Evolution  (CF17) = http://www.bristol.ac.uk/study/undergraduate/2018/geology/bsc-palaeontology-and-evolution/",
"BSc                Philosophy and Economics  (VL51) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/bsc-philosophy-econ/",
"BA                Philosophy and French  (RV15) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-french/",
"BA                Philosophy and Italian  (RV35) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-italian/",
"BA                Philosophy and Portuguese  (RV55) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-portuguese/",
"BA                Philosophy and Spanish  (RV45) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-spanish/",
"BSc                Philosophy and Politics  (VL52) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-philosophy-politics/",
"BA                Philosophy and Theology  (VV56) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-theology/",
"MSci                Physics  (F303) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics/",
"BSc                Physics  (F300) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics/",
"BA                Philosophy and Russian  (RV75) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-russian/",
"BSc                Physics and Philosophy  (FV35) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics-philosophy/",
"BSc                Physics with Astrophysics  (F3F5) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics-astrophysics/",
"MSci                Physics with Astrophysics  (F3FM) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-astrophysics/",
"MSci                Physics with Industrial Experience  (F305) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-industry/",
"MSci                Physics and Philosophy  (FVH5) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-philosophy/",
"MSci                Physics with Study in Continental Europe  (F304) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-europe/",
"BSc                Physics with a Preliminary Year of Study  (F308) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/bsc-physics-preliminary-study/",
"BSc                Physiological Science  (B120) = http://www.bristol.ac.uk/study/undergraduate/2018/physiology/bsc-physiology-science/",
"MSci                Physiological Science with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/physiology/msci-physiological-science-industry/",
"BSc                Neuroscience  (B140) = http://www.bristol.ac.uk/study/undergraduate/2018/neuroscience/bsc-neuroscience/",
"BA                Politics and French  (RL12) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-french/",
"BA                Politics and German  (RL22) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-german/",
"MSci                Physics with Innovation  (F306) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-physics-with-innovation/",
"BSc                Politics and International Relations  (L200) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-politics-international-relations/",
"BSc                Politics and International Relations with Study Abroad  (L201) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-politics-and-international-relations-with-stu/",
"BA                Politics and Portuguese  (RL52) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-portuguese/",
"BA                Politics and Russian  (RL72) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-russian/",
"BA                Politics and Spanish  (RL42) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-spanish/",
"BA                Politics and Italian  (RL32) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/ba-politics-italian/",
"BSc                Politics with Quantitative Research Methods  (L202) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-politics-quantitative-research/",
"MSci                Politics with Quantitative Research Methods  (L203) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-politics-quantitative-research/",
"BSc                Politics with Quantitative Research Methods with Study Abroad  (L204) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-politics-with-quantitative-research-methods-w/",
"BSc                Psychology  (C801) = http://www.bristol.ac.uk/study/undergraduate/2018/psychology/bsc-psychology/",
"BSc                Psychology in Education  (X301) = http://www.bristol.ac.uk/study/undergraduate/2018/education/bsc-psychology-in-education/",
"MSci                Psychology with Innovation  (C804) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/msci-psychology-with-innovation/",
"BA                Religion and Theology  (V600) = http://www.bristol.ac.uk/study/undergraduate/2018/religion-theology/ba-religion-theology/",
"MArts                Religion and Theology with Study Abroad  (V601) = http://www.bristol.ac.uk/study/undergraduate/2018/religion-theology/marts-religion-and-theology-with-study-abroad/",
"MSci                Psychology  (C802) = http://www.bristol.ac.uk/study/undergraduate/2018/psychology/msci-psychology/",
"BA                Russian  (R700) = http://www.bristol.ac.uk/study/undergraduate/2018/russian/ba-russian/",
"MSci                Physics with International Experience  (F307) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-physics-with-international-experience/",
"BA                Russian and Portuguese  (RR57) = http://www.bristol.ac.uk/study/undergraduate/2018/russian/ba-russian-portuguese/",
"BSc                Social Policy  (L400) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy/",
"BSc                Social Policy and Politics  (LL42) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-politics/",
"BSc                Social Policy with Criminology  (LM49) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-with-criminology/",
"BSc                Social Policy with Quantitative Research Methods  (L402) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-social-policy-quantitative-research/",
"MSci                Social Policy with Quantitative Research Methods  (L403) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-social-policy-quantitative-research/",
"BSc                Social Policy and Sociology  (LL43) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-sociology/",
"BSc                Social Policy with Study Abroad  (L404) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-with-study-abroad/",
"BSc                Sociology  (L300) = http://www.bristol.ac.uk/study/undergraduate/2018/sociology/bsc-sociology/",
"BSc                Social Policy with Management  (LN42) = http://www.bristol.ac.uk/study/undergraduate/2018/social-policy/bsc-social-policy-management/",
"BSc                Sociology and Philosophy  (LV35) = http://www.bristol.ac.uk/study/undergraduate/2018/sociology/bsc-sociology-philosophy/",
"BSc                Sociology with Quantitative Research Methods  (L302) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-sociology-quantitative-research/",
"BSc                Sociology with Quantitative Research Methods with Study Abroad  (L304) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/bsc-sociology-with-quantitative-research-methods-/",
"BSc                Sociology with Study Abroad  (L301) = http://www.bristol.ac.uk/study/undergraduate/2018/sociology/bsc-sociology-study-abroad/",
"BSc                Politics and Sociology  (LL23) = http://www.bristol.ac.uk/study/undergraduate/2018/politics-international-relations/bsc-politics-sociology/",
"BA                Spanish and Portuguese  (RR54) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-spanish-portuguese/",
"MSci                Sociology with Quantitative Research Methods  (L303) = http://www.bristol.ac.uk/study/undergraduate/2018/quantitative-research-methods/msci-sociology-quantitative-research/",
"BA                Spanish and Russian  (RR47) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-spanish-russian/",
"BA                Theatre and English  (4CC8) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-english/",
"BA                Theatre and Film  (4KDU) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-film/",
"BA                Spanish  (R400) = http://www.bristol.ac.uk/study/undergraduate/2018/spanish/ba-spanish/",
"BA                Theatre and German  (21C7) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-german/",
"BA                Theatre and Performance Studies  (2Q3W) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-performance/",
"BA                Theatre and Portuguese  (R2D8) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-portuguese/",
"BA                Theatre and Spanish  (4D8C) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-spanish/",
"BA                Theatre and Italian  (22FF) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-italian/",
"BA                Theology and Sociology  (VL63) = http://www.bristol.ac.uk/study/undergraduate/2018/religion-theology/ba-theology-sociology/",
"MSci                Theoretical Physics  (F340) = http://www.bristol.ac.uk/study/undergraduate/2018/physics/msci-theoretical-physics/",
"BSc                Veterinary Nursing and Bioveterinary Science  (DC37) = http://www.bristol.ac.uk/study/undergraduate/2018/vet-nursing-biovet-science/bsc-vet-nursing/",
"MArts                Theatre with Innovation  (2Q50) = http://www.bristol.ac.uk/study/undergraduate/2018/innovation/marts-theatre-with-innovation/",
"BVSc                Veterinary Science  (D100) = http://www.bristol.ac.uk/study/undergraduate/2018/vet-science/bvsc-veterinary-science/",
"BA                Theatre and French  (W43F) = http://www.bristol.ac.uk/study/undergraduate/2018/theatre/ba-theatre-french/",
"BSc                Virology and Immunology  (C540) = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-virology-immunology/",
"BSc                Virology and Immunology with Study in Industry = http://www.bristol.ac.uk/study/undergraduate/2018/cellular-molecular/bsc-virology-and-immunology-with-study-in-industry/",
"BSc                Zoology  (C300) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/bsc-zoology/",
"MSci                Zoology  (C303) = http://www.bristol.ac.uk/study/undergraduate/2018/biological-sciences/msci-zoology/",
"BA                Philosophy and German  (RV25) = http://www.bristol.ac.uk/study/undergraduate/2018/philosophy/ba-philosophy-german/", ]
l = list(set(l))
p = []
d = []
for i in l:
    p.append(i.split('=')[0])
    d.append(i.split('=')[1])
# print(p)
# print(len(p))
# print(d)
# print(len(d))